export {
  getData,
  postData,
  updateSmurfs,
  FETCH_SMURF_DATA_START,
  FETCH_SMURF_DATA_SUCCESS,
  FETCH_SMURF_DATA_FAILURE,
  POST_SMURF_DATA_START,
  POST_SMURF_DATA_SUCCESS,
  POST_SMURF_DATA_FAILURE,
  UPDATE_SMURF,
} from './FormActions';
